import type { DisasterEvent, Shelter } from "./types";

const NOW = new Date().toISOString();

export const SEEDED_DISASTER: DisasterEvent = {
  id: "flood-rock-wi-2026-05-02",
  event_type: "Flood Warning",
  title: "Flood Warning",
  severity: "SEVERE",
  urgency: "IMMEDIATE",
  location_name: "Rock, WI",
  county: "Rock",
  state: "WI",
  latitude: 42.6828,
  longitude: -89.0187,
  affected_radius_miles: 25,
  affected_population: 152586,
  description:
    "Flood Warning issued May 2 at 4:22PM CDT by NWS Milwaukee/Sullivan WI",
  source: "NWS Milwaukee/Sullivan WI",
  issued_at: NOW,
  expires_at: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
  created_at: NOW,
};

export const SEEDED_SHELTERS: Shelter[] = [
  {
    id: "s1",
    name: "Rock County Emergency Shelter",
    address: "100 Main St",
    city: "Janesville",
    state: "WI",
    latitude: 42.6825,
    longitude: -89.028,
    capacity: 800,
    current_occupancy: 640,
    wheelchair_accessible: true,
    has_medical_support: true,
    has_power_backup: true,
    has_transportation_support: true,
    has_interpreters: true,
    created_at: NOW,
  },
  {
    id: "s2",
    name: "Janesville Community Center",
    address: "200 Center Ave",
    city: "Janesville",
    state: "WI",
    latitude: 42.6902,
    longitude: -89.022,
    capacity: 550,
    current_occupancy: 475,
    wheelchair_accessible: true,
    has_medical_support: false,
    has_power_backup: true,
    has_transportation_support: true,
    has_interpreters: false,
    created_at: NOW,
  },
  {
    id: "s3",
    name: "Beloit High School Shelter",
    address: "1225 Fourth St",
    city: "Beloit",
    state: "WI",
    latitude: 42.5143,
    longitude: -89.0323,
    capacity: 700,
    current_occupancy: 390,
    wheelchair_accessible: true,
    has_medical_support: true,
    has_power_backup: false,
    has_transportation_support: false,
    has_interpreters: true,
    created_at: NOW,
  },
  {
    id: "s4",
    name: "Milton Senior Center",
    address: "10 Parkview Dr",
    city: "Milton",
    state: "WI",
    latitude: 42.7736,
    longitude: -88.9437,
    capacity: 230,
    current_occupancy: 205,
    wheelchair_accessible: true,
    has_medical_support: true,
    has_power_backup: true,
    has_transportation_support: true,
    has_interpreters: false,
    created_at: NOW,
  },
  {
    id: "s5",
    name: "Mercyhealth Emergency Support Site",
    address: "1000 Mineral Point Ave",
    city: "Janesville",
    state: "WI",
    latitude: 42.6954,
    longitude: -89.0108,
    capacity: 420,
    current_occupancy: 301,
    wheelchair_accessible: true,
    has_medical_support: true,
    has_power_backup: true,
    has_transportation_support: true,
    has_interpreters: true,
    created_at: NOW,
  },
];
